language: node_js
node_js:
  - node
script:
  - yarn run lint
  - yarn run cover
  - yarn run build
  - yarn run bundlesize
after_success: yarn run coveralls
cache: yarn
branches:
  except:
    - /^Publish/
